version: "3"

services:
  bundle:
    container_name: fpc-bundle
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3004:3004"
  redis:
    image: redis/redis-stack-server
