export default function Head() {
    return (
        <>
            <title>FPL clock</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <link rel="icon" href="/favicon.ico"/>
        </>
    )
}
